/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autores.vistas;

import autores.modelos.Cargo;
import autores.modelos.ModeloComboCargos;
import autores.modelos.Profesor;
import java.awt.Dialog;
import java.util.ArrayList;
import javax.swing.JDialog;

public class VentanaAMAlumno extends JDialog {
    ArrayList<Profesor> profesores = new ArrayList<>();
    
    /**
     * Constructor
     * @param ventanaPadre ventana padre
     */
    public VentanaAMAlumno(Dialog ventanaPadre) {
        super(ventanaPadre, true);
        initComponents();
//        this.comboBoxCargo.setModel(new ModeloComboCargos());
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtApellidosNuevoAlumno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombresNuevoAlumno = new javax.swing.JTextField();
        btnGuardarNuevoAlumno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDNINuevoAlumno = new javax.swing.JTextField();
        txtClaveNuevoAlumno = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRepetirClaveNuevoAlumno = new javax.swing.JPasswordField();
        btnCancelarNuevoAlumno = new javax.swing.JButton();
        txtCXNuevoAlumno = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Profesores");
        setResizable(false);

        jLabel1.setText("Apellidos:");

        txtApellidosNuevoAlumno.setToolTipText("Apellidos del profesor");

        jLabel2.setText("Nombres:");

        txtNombresNuevoAlumno.setToolTipText("Nombres del profesor");

        btnGuardarNuevoAlumno.setMnemonic('G');
        btnGuardarNuevoAlumno.setText("Guardar");
        btnGuardarNuevoAlumno.setToolTipText("");
        btnGuardarNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNuevoAlumnoClic(evt);
            }
        });

        jLabel3.setText("CX");

        jLabel4.setText("Documento:");

        txtDNINuevoAlumno.setToolTipText("Documento del profesor");

        jLabel6.setText("Clave:");

        jLabel7.setText("Repetir clave:");

        btnCancelarNuevoAlumno.setText("Cancelar");
        btnCancelarNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNuevoAlumnoActionPerformed(evt);
            }
        });

        txtCXNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCXNuevoAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRepetirClaveNuevoAlumno)
                            .addComponent(txtNombresNuevoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(txtDNINuevoAlumno)
                            .addComponent(txtApellidosNuevoAlumno)
                            .addComponent(txtClaveNuevoAlumno)
                            .addComponent(txtCXNuevoAlumno)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarNuevoAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarNuevoAlumno)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNINuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidosNuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombresNuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCXNuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClaveNuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRepetirClaveNuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarNuevoAlumno)
                    .addComponent(btnCancelarNuevoAlumno)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarNuevoAlumnoClic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNuevoAlumnoClic
        int dni = 0;
        if (!this.txtDNINuevoAlumno.getText().trim().isEmpty())
            dni = Integer.parseInt(this.txtDNINuevoAlumno.getText().trim());
        String apellidos = this.txtApellidosNuevoAlumno.getText().trim();
        String nombres = this.txtNombresNuevoAlumno.getText().trim();
        //Por qué necesito que sea static el método toCargo?
        //Cargo cargo = Cargo.toCargo(this.comboBoxCargoNuevoProfesor.getSelectedItem().toString().toUpperCase());
        String clave = new String(this.txtClaveNuevoAlumno.getPassword());
        //Profesor profesor = new Profesor(dni, apellidos, nombres, clave, cargo);
        //this.profesores.add(profesor);
        //for(Profesor p : this.profesores)
            //p.mostrar();
    }//GEN-LAST:event_btnGuardarNuevoAlumnoClic

    private void btnCancelarNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNuevoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarNuevoAlumnoActionPerformed

    private void txtCXNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCXNuevoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCXNuevoAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarNuevoAlumno;
    private javax.swing.JButton btnGuardarNuevoAlumno;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtApellidosNuevoAlumno;
    private javax.swing.JTextField txtCXNuevoAlumno;
    private javax.swing.JPasswordField txtClaveNuevoAlumno;
    private javax.swing.JTextField txtDNINuevoAlumno;
    private javax.swing.JTextField txtNombresNuevoAlumno;
    private javax.swing.JPasswordField txtRepetirClaveNuevoAlumno;
    // End of variables declaration//GEN-END:variables
}
